REVOKE ALL PRIVILEGES ON DATABASE osm FROM render;

\c osm
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM render;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM render;
GRANT USAGE ON SCHEMA public TO render;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO render;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO render;
GRANT ALL ON SCHEMA public TO import;
GRANT ALL ON DATABASE osm TO import;
GRANT CONNECT ON DATABASE osm TO render;
